### ISSUE TITLE
🌟 [me, scrap 페이지 로딩 스켈레톤 및 수정사항 반영]

### ISSUE THREAD

**Issue by aoooec** [hyeonji1125/sfacspace-06-project#108]
## 요약
- 페이지 내부 데이터 통신이 필요한 아이템의 스켈레톤 UI 적용
- 일부 `UI` 수정 
- 일부 컴포넌트 기능 수정  

## ToDo

- [x] `dropdown` UI, 기능 수정
- [x] UserItem 스켈레톤 적용
- [x] Articles(scraplist) 스켈레톤 적용
- [x] 기타 css 수정 
- [x] 데이터가 없을 경우 보여줄 UI
