### ISSUE TITLE
🌟 [contact form 수정사항 반영]

### ISSUE THREAD

**Issue by aoooec** [hyeonji1125/sfacspace-06-project#112]
## 요약
- 랜딩, contact 페이지에서 사용하는 form 컴포넌트 수정사항 반영 

## ToDo
- [x] vallidation rule 적용
- [x] form submit 이후 로그인 상태에서 name, email 초기화되는 오류 수정 
- [x] submit complete 모달 추가
