### ISSUE TITLE
🌟 [디렉토리 구조 수정 + 빌드 오류 수정 + Floating 버튼 구현]

### ISSUE THREAD

**Issue by ko9612** [hyeonji1125/sfacspace-06-project#3]
## 요약
e.g) 유저 컴포넌트 구현

## ToDo
- [x] 디렉토리 구조 수정 및 png -> svg파일로 수정
- [x] 빌드 오류 수정
- [x] floating 버튼(Top button, chatbot button) // 스토리북 적용x
