### ISSUE TITLE
🌟 [마이페이지(repos) 수정 및 기능구현]

### ISSUE THREAD

**Issue by aoooec** [hyeonji1125/sfacspace-06-project#70]
## 요약
- 마이페이지 레포지토리 리스트 출력 및 유저 인터랙션 관련 로직 구현 및 수정 

## ToDo
- [x] 1차 구현
- [x] 유저 인터랙션에 있는 값을 `DB` `repos`에 별도 저장하도록 수정 
- [x] 리스트에서 `github data`와 `DB repos`를 가져와 조건에 따라 `UI` 변경될 수 있도록 수정 
- [x] `sort`, `filter` 로직을 바꾼 데이터 방식에 따라 수정
